name: Update README

on:
  schedule:
    # Запускається щодня о 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Дозволяє запускати вручну
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Отримуємо поточну дату та час
        current_date=$(date +'%d.%m.%Y')
        current_time=$(date +'%H:%M:%S UTC')
        
        # Отримуємо рандомну цитату
        quote=$(curl -s "https://api.quotable.io/random" | grep -o '"content":"[^"]*' | sed 's/"content":"//')
        
        # Отримуємо GitHub статистику
        github_user="${{ github.repository_owner }}"
        
        # Отримуємо загальну кількість комітів
        total_commits=$(curl -s "https://api.github.com/search/commits?q=author:$github_user" | grep -o '"total_count":[^,]*' | sed 's/"total_count"://')
        
        # Отримуємо інформацію про репозиторії
        repo_stats=$(curl -s "https://api.github.com/users/$github_user")
        public_repos=$(echo $repo_stats | grep -o '"public_repos":[^,]*' | sed 's/"public_repos"://')
        
        # Оновлюємо README.md
        sed -i "s/{CURRENT_DATE}/$current_date/g" README.md
        sed -i "s/{CURRENT_TIME}/$current_time/g" README.md
        sed -i "s/{QUOTE_OF_DAY}/$quote/g" README.md
        sed -i "s/{TOTAL_COMMITS}/$total_commits/g" README.md
        sed -i "s/{PUBLIC_REPOS}/$public_repos/g" README.md
        sed -i "s/YOUR_USERNAME/$github_user/g" README.md
        
        # Додаємо зміни до git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git diff --staged --quiet || git commit -m "🤖 Auto update README - $(date +'%Y-%m-%d %H:%M:%S')"
        git push
